### ISSUE TITLE
Use with x-for array of objects 

### ISSUE THREAD

**Issue by andyjamesn** [loomchild/webflow-alpinejs#3]
I created a test case using jsonplaceholder data. I can get x-for to work but only the first item inside x-for using v-text gets displayed

This is the data.

https://jsonplaceholder.typicode.com/users

I am binding it to an alpineinstance using x-init

Here is a preview of the test page

https://preview.webflow.com/preview/alpine-test-7aa881?utm_medium=preview_link&utm_source=designer&utm_content=alpine-test-7aa881&preview=af921821a86a75e700fdfc79d32cbb6b&pageId=60ec6c1fc7c8088da694d384&workflow=preview

The template getting created looks correct

```
<template x-for="user in users" x-bind:key="user.id">
    <p x-text="user.name" class="name">name</p>
    <p x-text="user.username" class="username">username</p>
</template>
```

The name is being output but not the username. If I swap them around in Webflow then only the username shows

There seems to be some kind of render issue with the <template> in webflow.. any ideas?

**Comment by loomchild** [comment]
I think template needs to contain only single element root. Can you try to wrap the paragraphs in a `div`?

**Comment by andyjamesn** [comment]
Yep that seems to have solved it. Thanks

**Comment by loomchild** [comment]
No worries, I think this Alpine.js limitation could be better documented / there could be an error message. I will try to reach out to them when I have a chance.
