### ISSUE TITLE
hello I try to do a loop within a loop

### ISSUE THREAD

**Issue by oswaldB** [loomchild/webflow-alpinejs#6]
Hello,

First of all super great work!

I need to do a x-for within a x-for and it is not working.

Have you planed this scenario? Is it working for you ?

Thank you very much

**Comment by loomchild** [comment]
It's even simpler in version 2 of the library (you need to change the dependencies). Instead of replacing a div by template, I am wrapping it in a template instead. Thanks to this 3rd div is no loner necessary. I have updated the example as well.
